In [2]:
import os
import torch
os.environ['CUDA_VISIBLE_DEVICES'] = "0"
torch.cuda.set_device(0)

In [3]:
from model import BertForMultiHeadModel
from transformers import BertTokenizerFast

In [6]:
model = BertForMultiHeadModel.from_pretrained('test/checkpoint-4000')
tokenizer = BertTokenizerFast.from_pretrained('bert-base-german-cased')

Some weights of BertForMultiHeadModel were not initialized from the model checkpoint at test/checkpoint-4000 and are newly initialized: ['.bert.embeddings.position_ids', '.bert.embeddings.word_embeddings.weight', '.bert.embeddings.position_embeddings.weight', '.bert.embeddings.token_type_embeddings.weight', '.bert.embeddings.LayerNorm.weight', '.bert.embeddings.LayerNorm.bias', '.bert.encoder.layer.0.attention.self.query.weight', '.bert.encoder.layer.0.attention.self.query.bias', '.bert.encoder.layer.0.attention.self.key.weight', '.bert.encoder.layer.0.attention.self.key.bias', '.bert.encoder.layer.0.attention.self.value.weight', '.bert.encoder.layer.0.attention.self.value.bias', '.bert.encoder.layer.0.attention.output.dense.weight', '.bert.encoder.layer.0.attention.output.dense.bias', '.bert.encoder.layer.0.attention.output.LayerNorm.weight', '.bert.encoder.layer.0.attention.output.LayerNorm.bias', '.bert.encoder.layer.0.intermediate.dense.weight', '.bert.encoder.layer.0.intermediate.

In [7]:
import pandas as pd
df_val = pd.read_json('../data/imdb_val.json')

In [ ]:
for i in range(5):
    index = i
    print(df_val.iloc[index])
    text = df_val.iloc[index].text
    print(text[:10])
    inputs = tokenizer(text, return_tensors='pt', truncation=True)
    #inputs = inputs.to('cuda:0')
    with torch.no_grad():
        outputs = model(**inputs)
    print(torch.softmax(outputs.classification_logits, dim=-1).view(-1))
    print(torch.sigmoid(outputs.multilabels_logits).view(-1).topk(k=3))
    print(outputs.regression_logits.view(-1))
    print("#"*200)

text              Bisher bei The Americans... - Ihre Großtante? ...
IMDB_ID                                                   tt3459862
genre                                              [Crime, Mystery]
year                                                           2014
duration                                                         45
titleType                                                 tvEpisode
primaryTitle                                            The Walk-In
isAdult                                                           0
runtimeMinutes                                                   45
averageRating                                                   8.1
numVotes                                                       1149
Name: 0, dtype: object
Bisher bei
tensor([0.4289, 0.5711])
torch.return_types.topk(
values=tensor([0.6412, 0.6368, 0.6175]),
indices=tensor([12, 10,  3]))
tensor([0.1659])
################################################################################

In [9]:
torch.softmax(outputs.classification_logits, dim=-1).view(-1)

tensor([0.4377, 0.5623])

In [10]:
torch.sigmoid(outputs.multilabels_logits).view(-1).topk(k=3)

torch.return_types.topk(
values=tensor([0.6503, 0.6386, 0.6247]),
indices=tensor([12, 10,  3]))

In [11]:
outputs.regression_logits.view(-1)

tensor([0.1988])

In [12]:
torch.randn(16, 10).topk(k=3).indices.size()

torch.Size([16, 3])