In [1]:
import os
import torch
from transformers import Trainer, TrainingArguments, TrainerCallback
from transformers import BertTokenizerFast, BertForTokenClassification
from transformers import set_seed
from datasets import load_from_disk, load_dataset
from torch.nn import functional as F

os.environ['CUDA_VISIBLE_DEVICES'] = "0"
torch.cuda.set_device(0)

In [10]:
model = BertForTokenClassification.from_pretrained('test/checkpoint-18000/')

In [11]:
tokenizer = BertTokenizerFast.from_pretrained('bert-base-cased')

In [12]:
test_story = "When he got home he noticed he couldn't get up! He drove and picked up his food. He put the bag in his lap and started to drive home. The sauce had leaked out and made him stuck! Ray wanted to order Chinese food."

In [13]:
from nltk import sent_tokenize
sents = sent_tokenize(test_story, language='english')
shuffled_sents = sents[::-1]
shuffled_text = ' [CLS] '+ ' [CLS] '.join(shuffled_sents)
print(shuffled_text)

 [CLS] Ray wanted to order Chinese food. [CLS] The sauce had leaked out and made him stuck! [CLS] He put the bag in his lap and started to drive home. [CLS] He drove and picked up his food. [CLS] When he got home he noticed he couldn't get up!


In [14]:
inputs = tokenizer(shuffled_text, add_special_tokens=False, return_tensors='pt')

In [15]:
outputs = model(**inputs)

In [16]:
logits = outputs['logits']
input_ids = inputs['input_ids']

In [17]:
target_logits = logits[input_ids == tokenizer.cls_token_id]
target_logits

tensor([[2.4028],
        [2.4028],
        [2.4028],
        [2.4028],
        [2.4028]], grad_fn=<IndexBackward>)

In [18]:
target_logits.reshape(-1).argsort()

tensor([2, 3, 1, 4, 0])

In [62]:
test

NameError: name 'test' is not defined

In [63]:
from datasets import load_from_disk

In [70]:
dataset = load_from_disk('../data/rocstories/')

In [72]:
dataset['val']

Dataset({
    features: ['sentence1', 'sentence2', 'sentence3', 'sentence4', 'sentence5', 'so_targets', 'storyid', 'storytitle', 'text'],
    num_rows: 3
})

In [67]:
dir(dataset['val'])

['__class__',
 '__del__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_check_index_is_initialized',
 '_data',
 '_fingerprint',
 '_format_columns',
 '_format_kwargs',
 '_format_type',
 '_get_cache_file_path',
 '_getitem',
 '_indexes',
 '_indices',
 '_info',
 '_map_single',
 '_new_dataset_with_indices',
 '_output_all_columns',
 '_split',
 'add_column',
 'add_elasticsearch_index',
 'add_faiss_index',
 'add_faiss_index_from_external_arrays',
 'add_item',
 'align_labels_with_mapping',
 'builder_name',
 'cache_files',
 'cast',
 'cast_',
 'citation',
 'class_encode_column',
 'cleanup_cache_files',
 'column_names',
 'c

In [83]:
import numpy as np

sent_idx = np.array([
    [0, 2, 3, -100, -100],
    [1, 0, -100, -100, -100],
    [0, 2, 3, 4, -100],
])
logits = np.random.randn(3, 512, 1)
sent_idx.shape, logits.shape

((3, 5), (3, 512, 1))

In [80]:
.shape

(3, 512)

In [82]:
sent_idx[sent_idx != -100]

array([0, 2, 3, 1, 0, 0, 2, 3, 4])

In [34]:
from torch import nn
loss = nn.MSELoss(reduction='mean')
loss(torch.tensor([1.0, 1.5]), torch.tensor([0.0, 2.0]))

tensor(0.6250)

In [32]:
loss(torch.tensor([[1.0], [1.5]]), torch.tensor([[0.0], [2.0]])).reshape(-1)

tensor([1.0000, 0.2500])

In [38]:
test = torch.arange(6).reshape(2, 3)
test

tensor([[0, 1, 2],
        [3, 4, 5]])

In [39]:
test.sum(axis=0)

tensor([3, 5, 7])

In [46]:
torch.tensor([[0], [1], [2]]).reshape(-1, 1, 1).shape

torch.Size([3, 1, 1])